### ISSUE TITLE
Merge TODO and remove file.

### ISSUE THREAD

**Issue by ozgurozbek** [ozgurozbek/teothe#66]
- [x] Added incomplete tasks to milestone 2.0

# A list of previous completed tasks:
## 1.4

- [x] Fix navbar height and text size
- [x] Fix navbar active tab display style
- [x] Fix navbar build errors
- [x] Menu always shows the active tab after clicking main image
- [x] PWA (Web app manifest or service worker do not meet the installability requirements, Failures: No manifest was fetched.)
- [x] Fix deities page to fetch only once - it already fetches once because of NextJS

## 1.3.2

- [x] When minimized, sidenav always shows the tab name after clicking it
- [x] When minimized and landscape, sidenav does not fit the screen
- [x] 3 more races to backend
- [x] Deities images use image in avatar, need to have square deity images
- [x] next-size-adjust meta tag - needs testing

## 1.3

- [x] Improve page title, too short + single word
- [x] more words in the main page, maybe we can provide a campaign setting text
- [x] Robots.txt

## 1.2

- [x] Look into tests - Not necessary for the time being, backend has 100% coverage
- [x] Function comment coverage - is its own branch
- [x] Some thematic background for the main page
- [x] rgba instead of 8 digit HEX colouring
- [x] Races page responsive (sm screen)
- [x] Page Top scroll smooth tailwind
- [x] Look for things to add to TODO
- [x] CalendarCell.tsx images don't have alt prop
- [x] split from --- in session notes
- [x] CalendarCell.tsx scroll
- [x] calendar year input css
- [x] PageCalendar onchange
- [x] Map zoom idea bounce
- [x] SideNav icon sizes (didnt work), timeout (looked horrible), skeleton (cant hook)

## 1.1

- [x] Planes wheel update to show holes\*
- [x] Scroll to top button
- [x] Sidenav collapsed not working
- [x] Common lore does not have the Planes wheel
- [x] Map description tooltips to bottom instead of top
- [x] Races page image alt fix
- [x] Fix logo image size
- [x] Make logo onclick to display nothing
- [x] Logo responsive on sidenav chage
- [x] make sidenav size change respect tailwind
- [x] layout sidenav loc changes
- [x] menu image transition
- [x] SideNav fixed to top
- [x] Layout>hasSider(bool): Whether contain Sider in children, don't have to assign it normally. Useful in ssr avoid style flickering

## Release

- [x] Map descriptions: There is no easy way of doing this simply without changing page layout. I mean, it is for the best as the DM should describe them, it'd be bad if the map described itself. Some exceptions have their icons changed and now use tooltips.
- [x] Fill races table (BE): Not all of them, most common and basic ones are fine.
- [x] Mobile: library css things - This worked fine?
- [x] Library page looks improved
- [x] Races pages Homebrew switch has the same color when On and Off
- [x] Delete Quest Page
- [x] Antd Loading..
- [x] Move backend into pythonanywhere
- [x] Compile and move FE build to github pages

## InDev

- [x] Add TODO
- [x] Place emotional echoes
- [x] Split maps
- [x] Export base
- [x] Export climates
- [x] Export resources
- [x] Export echoes
- [x] Export kingdoms
- [x] Export places
- [x] Export travel routes
- [x] Export cities
- [x] Export steamcart
- [x] Export continents
- [x] Export compass
- [x] Mobile force landscape, i guess
- [x] Mobile planes of existence div heights
- [x] SideNav is not crawlable
- [x] SideNav logo has no width & height
- [x] Add cooking table (BE)
- [x] Update table descriptions
- [x] Add cooking table to tables
- [x] Races tab Homebrew button is inline with other elements that shifts the Human entry; fix
- [x] Races tab homebrew text is not split by underscore to p elements
- [x] SideNav icons shift when collapsed
- [x] Library JS import somehow
- [x] Library PDFleri ve renderi
- [x] Homebrews page icon
- [x] Homebrews page
- [x] Deity images crop to fit
- [x] Races show hide homebrews (state ig)
- [x] Add pricing icon
- [x] Common pricing table (BE)
- [x] Common pricing page
- [x] Common pricing table sort by price (ANTD Table)
- [x] Some images have text in them in Locations, crop them
- [x] Add tools icon
- [x] Tools table (BE)
- [x] Display tools and actions available to them in a table
- [x] ./pages/PageMapOverlay.tsx Image elements must have an alt prop, either with meaningful text, or an empty string for decorative images.
- [x] ./src/app/layout.tsx Error: Synchronous scripts should not be used. See: [https://nextjs.org/docs/messages/no-sync-scripts] @next/next/no-sync-scripts

Close when todo file is removed and there is a commit in [`unique-routes`](https://github.com/ozgurozbek/teothe/tree/unique-routes)

**Comment by ozgurozbek** [comment]
Commit 624cd43a571a9a22c6dbd393b4d79f94d6c61465 in [`unique-routes`](https://github.com/ozgurozbek/teothe/tree/unique-routes)
